---

- hosts: website
  become: true
  pre_tasks:
  
  - name: Update Repository
    apt:
      update_cache: true
      upgrade: full
    changed_when: false

- hosts: website
  become: true
  tasks:

  - name: Install Apache, PHP support, Cron, Vim and Git
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_module }}"
        - "{{ cron }}"
        - "git"
        - "vim"
      state: latest
  
  - name: DuckDns setup
    copy:
      src: duckdns
      dest: "{{ home }}"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755
  
  - name: Cronjob
    cron:
      name: DuckDns
      user: "{{ user }}"
      minute: "*/5"
      job: "{{ home }}/duckdns/duck.sh > /dev/null 2>&1"

  - name: Empty html directory
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Git
    git:
      repo: "https://github.com/Veisakis/openhistory"
      dest: "/var/www/html/"
...
