---

- hosts: website
  become: true
  pre_tasks:
  
  - name: Update Repository for Debian (including Raspian)
    apt:
      update_cache: true
      upgrade: full
    when: ansible_distribution == "Debian"

  - name: Update Repository for RHEL
    dnf:
      update_cache: true
      update_only: true
    when: ansible_distribution == ["CentOS", "Fedora"]

- hosts: website
  become: true
  tasks:

  - name: Install Apache and PHP support
    package:
      name: 
        - {{ apache_package }}
        - {{ php_module }}
      state: latest
  
  - name: DuckDns setup
    copy:
      src: duckdns
      dest: {{ home }}
      owner: {{ user }}
      group: {{ group }}
      mode: 755

...
